language: python
python:
  - "3.8"  
  
addons:
  sonarcloud:
    organization: "jabertuhin"
    token:
      secure: $SONAR_TOKEN
    branches:
      - development

# command to install dependencies
install:
  - pip install -r requirements.dev.txt
# command to run tests
script:
  - pytest --cov-report xml --cov=app tests/
  - export SONARQUBE_SKIPPED=false
  - sonar-scanner
